//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace charmap.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Coordinates : global::System.Configuration.ApplicationSettingsBase {
        
        private static Coordinates defaultInstance = ((Coordinates)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Coordinates())));
        
        public static Coordinates Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point sliderTopLeft {
            get {
                return ((global::System.Drawing.Point)(this["sliderTopLeft"]));
            }
            set {
                this["sliderTopLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point sliderBottomRight {
            get {
                return ((global::System.Drawing.Point)(this["sliderBottomRight"]));
            }
            set {
                this["sliderBottomRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point smallFurnaceTopLeft {
            get {
                return ((global::System.Drawing.Point)(this["smallFurnaceTopLeft"]));
            }
            set {
                this["smallFurnaceTopLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point smallFurnaceBottomRight {
            get {
                return ((global::System.Drawing.Point)(this["smallFurnaceBottomRight"]));
            }
            set {
                this["smallFurnaceBottomRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point largeFurnaceTopLeft {
            get {
                return ((global::System.Drawing.Point)(this["largeFurnaceTopLeft"]));
            }
            set {
                this["largeFurnaceTopLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point largeFurnaceBottomRight {
            get {
                return ((global::System.Drawing.Point)(this["largeFurnaceBottomRight"]));
            }
            set {
                this["largeFurnaceBottomRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point slotTopLeft {
            get {
                return ((global::System.Drawing.Point)(this["slotTopLeft"]));
            }
            set {
                this["slotTopLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point slotBottomRight {
            get {
                return ((global::System.Drawing.Point)(this["slotBottomRight"]));
            }
            set {
                this["slotBottomRight"] = value;
            }
        }
    }
}
